services:
  example:
    image: caddy:2.6.3-alpine@sha256:77845149bcba28d31f045702daf6dfb1d84e61a1acb6fdfb12d2108f4d91de88
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: example.beta.fogtype.com
      caddy.reverse_proxy: "{{upstreams}}"
networks:
  caddy:
    external: true
