services:
  example:
    image: caddy:2.6.4-alpine@sha256:1d39948357ef8ba114c1620c2b5953fa0b4c3f13fec79cb10ccb1c01b2937a3a
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: example.beta.fogtype.com
      caddy.reverse_proxy: "{{upstreams}}"
networks:
  caddy:
    external: true
