services:
  example:
    image: caddy:2.6.3-alpine@sha256:ed81228ba91274f9af97ca5d41dafff1a9f1cfcedb6679377ea577c6540469b8
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: example.beta.fogtype.com
      caddy.reverse_proxy: "{{upstreams}}"
networks:
  caddy:
    external: true
