services:
  example:
    image: caddy:2.6.3-alpine@sha256:e782cdc152609a801ac266b687d8edf04ba03afcc79feab6b893b3cf70e58b25
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: example.beta.fogtype.com
      caddy.reverse_proxy: "{{upstreams}}"
networks:
  caddy:
    external: true
