services:
  example:
    image: caddy:2.6.3-alpine@sha256:7644356089c9fa49f484d986258316090faa7dce7fa7bcf5b90c065110ae3b9f
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: example.beta.fogtype.com
      caddy.reverse_proxy: "{{upstreams}}"
networks:
  caddy:
    external: true
