services:
  example:
    image: caddy:2.6.3-alpine@sha256:7e7286bb77df853f278887dd9159bd643abca8447ad4a0fddb4c48ec00a7e6cc
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: example.beta.fogtype.com
      caddy.reverse_proxy: "{{upstreams}}"
networks:
  caddy:
    external: true
